### ISSUE TITLE
TERMUX ERROR 

### ISSUE THREAD

**Issue by sasangeo** [BochilGaming/games-wabot#100]
> games-wabot@0.9.8 start
> node index.js

Starting...
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'cfonts'
Require stack:
- /data/data/com.termux/files/home/games-wabot/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (/data/data/com.termux/files/home/games-wabot/index.js:6:17)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/data/data/com.termux/files/home/games-wabot/index.js' ]
}

**Comment by sasangeo** [comment]
> games-wabot@0.9.8 start
> node index.js

Starting...
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'cfonts'
Require stack:
- /data/data/com.termux/files/home/games-wabot/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (/data/data/com.termux/files/home/games-wabot/index.js:6:17)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/data/data/com.termux/files/home/games-wabot/index.js' ]
}

**Comment by BochilGaming** [comment]
> > games-wabot@0.9.8 start
> > node index.js
> 
> Starting... node:internal/modules/cjs/loader:936 throw err; ^
> 
> Error: Cannot find module 'cfonts' Require stack:
> 
> * /data/data/com.termux/files/home/games-wabot/index.js
>   at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
>   at Function.Module._load (node:internal/modules/cjs/loader:778:27)
>   at Module.require (node:internal/modules/cjs/loader:1005:19)
>   at require (node:internal/modules/cjs/helpers:94:18)
>   at Object. (/data/data/com.termux/files/home/games-wabot/index.js:6:17)
>   at Module._compile (node:internal/modules/cjs/loader:1101:14)
>   at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
>   at Module.load (node:internal/modules/cjs/loader:981:32)
>   at Function.Module._load (node:internal/modules/cjs/loader:822:12)
>   at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [ '/data/data/com.termux/files/home/games-wabot/index.js' ]
>   }

```bash
npm install -g npm@6.14.14
npm install
node .
```
