### ISSUE TITLE
Sticker Error

### ISSUE THREAD

**Issue by overfy** [BochilGaming/games-wabot#204]
![Screenshot_260](https://user-images.githubusercontent.com/95896781/151670614-91f58d7c-fbfd-45ce-bdc8-a773b0812bf9.png)

Command Sticker Error ( Seperti Gambar Diatas ), ketika di coba reply pun tetap sama, 

Host : Repl.it

**Comment by overfy** [comment]
Log Saat Eksekusi Command Sticker
```
<Buffer 3c 73 63 72 69 70 74 20 74 79 70 65 3d 22 39 38 34 66 36 66 61 35 61 64 65 62 36 39 35 65 63 38 37 34 61 37 37 33 2d 74 65 78 74 2f 6a 61 76 61 73 63 ... 502866 more bytes>
<Buffer >
<Buffer 3c 21 44 4f 43 54 59 50 45 20 68 74 6d 6c 3e 0a 09 3c 68 74 6d 6c 3e 0a 09 20 20 3c 68 65 61 64 3e 0a 09 09 3c 6d 65 74 61 20 6e 61 6d 65 3d 22 76 69 ... 456 more bytes>
<!DOCTYPE html>
    <html>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta charset="utf-8">
        <title>Application Error</title>
        <style media="screen">
          html,body,iframe {
            margin: 0;
            padding: 0;
          }
          html,body {
            height: 100%;
            overflow: hidden;
          }
          iframe {
            width: 100%;
            height: 100%;
            border: 0;
          }
        </style>
      </head>
      <body>
        <iframe src="//www.herokucdn.com/error-pages/application-error.html"></iframe>
      </body>
    </html>
<Buffer 3c 73 63 72 69 70 74 20 74 79 70 65 3d 22 35 31 39 61 30 65 33 64 31 33 63 65 33 30 37 31 66 34 33 62 31 39 62 39 2d 74 65 78 74 2f 6a 61 76 61 73 63 ... 502866 more bytes>
<Buffer >
<Buffer 3c 21 44 4f 43 54 59 50 45 20 68 74 6d 6c 3e 0a 09 3c 68 74 6d 6c 3e 0a 09 20 20 3c 68 65 61 64 3e 0a 09 09 3c 6d 65 74 61 20 6e 61 6d 65 3d 22 76 69 ... 456 more bytes>
<!DOCTYPE html>
    <html>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta charset="utf-8">
        <title>Application Error</title>
        <style media="screen">
          html,body,iframe {
            margin: 0;
            padding: 0;
          }
          html,body {
            height: 100%;
            overflow: hidden;
          }
          iframe {
            width: 100%;
            height: 100%;
            border: 0;
          }
        </style>
      </head>
      <body>
        <iframe src="//www.herokucdn.com/error-pages/application-error.html"></iframe>
      </body>
    </html>
Gagal
```

**Comment by overfy** [comment]
![Screenshot_261](https://user-images.githubusercontent.com/95896781/151671790-106c4792-3161-436f-8ee6-98f451101d8b.png)

ketika di chat di personal hanya " gagal "

**Comment by unx21** [comment]
> ![Screenshot_261](https://user-images.githubusercontent.com/95896781/151671790-106c4792-3161-436f-8ee6-98f451101d8b.png)
> 
> ketika di chat di personal hanya " gagal "



![Screenshot_20220130-015338_WhatsApp](https://user-images.githubusercontent.com/84166927/151671903-474871f8-1187-4029-9fee-156d7a0982ab.png)



:v

**Comment by BlueShiYT** [comment]
> ![Screenshot_261](https://user-images.githubusercontent.com/95896781/151671790-106c4792-3161-436f-8ee6-98f451101d8b.png)
> 
> ketika di chat di personal hanya " gagal "

Sama w jga:v

**Comment by overfy** [comment]
> > ![Screenshot_261](https://user-images.githubusercontent.com/95896781/151671790-106c4792-3161-436f-8ee6-98f451101d8b.png)
> > ketika di chat di personal hanya " gagal "
> 
> ![Screenshot_20220130-015338_WhatsApp](https://user-images.githubusercontent.com/84166927/151671903-474871f8-1187-4029-9fee-156d7a0982ab.png)
> 
> :v

itu fix nya gimana ya gan wkwkwk

**Comment by unx21** [comment]
> > > ![Screenshot_261](https://user-images.githubusercontent.com/95896781/151671790-106c4792-3161-436f-8ee6-98f451101d8b.png)
> > > ketika di chat di personal hanya " gagal "
> > 
> > 
> > ![Screenshot_20220130-015338_WhatsApp](https://user-images.githubusercontent.com/84166927/151671903-474871f8-1187-4029-9fee-156d7a0982ab.png)
> > :v
> 
> itu fix nya gimana ya gan wkwkwk

Saya pake temux hehe

**Comment by overfy** [comment]
Ane udah coba run di windows problemnya tetep sama gan hehehehe

**Comment by unx21** [comment]
> Ane udah coba run di windows problemnya tetep sama gan hehehehe

[Pc gan ane gabut](https://wa.me/62887436568613)

**Comment by BochilGaming** [comment]
> ![Screenshot_260](https://user-images.githubusercontent.com/95896781/151670614-91f58d7c-fbfd-45ce-bdc8-a773b0812bf9.png)
> 
> Command Sticker Error ( Seperti Gambar Diatas ), ketika di coba reply pun tetap sama,
> 
> Host : Repl.it

apakah ffmpeg sudah diinstall?

**Comment by overfy** [comment]
> > ![Screenshot_260](https://user-images.githubusercontent.com/95896781/151670614-91f58d7c-fbfd-45ce-bdc8-a773b0812bf9.png)
> > Command Sticker Error ( Seperti Gambar Diatas ), ketika di coba reply pun tetap sama,
> > Host : Repl.it
> 
> apakah ffmpeg sudah diinstall?
``
ffmpeg & imagemagick udah ada gan, dulu engga kaya gini, baru sekitar 3-7 harian begini.

**Comment by BochilGaming** [comment]
> > > ![Screenshot_260](https://user-images.githubusercontent.com/95896781/151670614-91f58d7c-fbfd-45ce-bdc8-a773b0812bf9.png)
> > > Command Sticker Error ( Seperti Gambar Diatas ), ketika di coba reply pun tetap sama,
> > > Host : Repl.it
> > 
> > 
> > apakah ffmpeg sudah diinstall?
> > ``
> > ffmpeg & imagemagick udah ada gan, dulu engga kaya gini, baru sekitar 3-7 harian begini.

Ok, w coba cari tahu knp ✌️

**Comment by BochilGaming** [comment]
@overfy  22f155b ini nge fix gk??

**Comment by overfy** [comment]
> @overfy [22f155b](https://github.com/BochilGaming/games-wabot/commit/22f155b8795e1a1f35e7379bd6ad6a9774d80802) ini nge fix gk??

bentar gan, ane dari tadi mau scan new session error terus qr nya, setiap nge scan bukannya kebca muncul error 
```
TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of ArrayBuffer, Buffer, TypedArray, DataView, KeyObject, or CryptoKey. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at prepareSecretKey (node:internal/crypto/keys:570:11)
    at Cipheriv.createCipherWithIV (node:internal/crypto/cipher:133:9)
    at new Cipheriv (node:internal/crypto/cipher:243:3)
    at Object.createCipheriv (node:crypto:138:10)
    at Object.aesEncrypt (E:\Times\games-wabot\node_modules\@adiwajshing\baileys\lib\WAConnection\Utils.js:108:24)
    at WAConnection.sendBinary (E:\Times\games-wabot\node_modules\@adiwajshing\baileys\lib\WAConnection\0.Base.js:321:26)
    at WAConnection.<anonymous> (E:\Times\games-wabot\node_modules\@adiwajshing\baileys\lib\WAConnection\4.Events.js:86:18)
    at WAConnection.emit (node:events:390:28)
    at WAConnection.emit (E:\Times\games-wabot\node_modules\@adiwajshing\baileys\lib\WAConnection\4.Events.js:664:41) {
  code: 'ERR_INVALID_ARG_TYPE'
} unhandledRejection
TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of ArrayBuffer, Buffer, TypedArray, DataView, KeyObject, or CryptoKey. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at prepareSecretKey (node:internal/crypto/keys:570:11)
>
    at new Cipheriv (node:internal/crypto/cipher:243:3)
    at Object.createCipheriv (node:crypto:138:10)
    at Object.aesEncrypt (E:\Times\games-wabot\node_modules\@adiwajshing\baileys\lib\WAConnection\Utils.js:108:24)
    at WAConnection.sendBinary (E:\Times\games-wabot\node_modules\@adiwajshing\baileys\lib\WAConnection\0.Base.js:321:26)
    at WAConnection.<anonymous> (E:\Times\games-wabot\node_modules\@adiwajshing\baileys\lib\WAConnection\4.Events.js:87:18)
    at WAConnection.emit (node:events:390:28)
    at WAConnection.emit (E:\Times\games-wabot\node_modules\@adiwajshing\baileys\lib\WAConnection\4.Events.js:664:41) {
  code: 'ERR_INVALID_ARG_TYPE'
} unhandledRejection
TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of ArrayBuffer, Buffer, TypedArray, DataView, KeyObject, or CryptoKey. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at prepareSecretKey (node:internal/crypto/keys:570:11)
    at Cipheriv.createCipherWithIV (node:internal/crypto/cipher:133:9)
    at new Cipheriv (node:internal/crypto/cipher:243:3)
    at Object.createCipheriv (node:crypto:138:10)
    at Object.aesEncrypt (E:\Times\games-wabot\node_modules\@adiwajshing\baileys\lib\WAConnection\Utils.js:108:24)
    at WAConnection.sendBinary (E:\Times\games-wabot\node_modules\@adiwajshing\baileys\lib\WAConnection\0.Base.js:321:26)
    at WAConnection.<anonymous> (E:\Times\games-wabot\node_modules\@adiwajshing\baileys\lib\WAConnection\4.Events.js:88:18)
    at WAConnection.emit (node:events:390:28)
    at WAConnection.emit (E:\Times\games-wabot\node_modules\@adiwajshing\baileys\lib\WAConnection\4.Events.js:664:41) {
  code: 'ERR_INVALID_ARG_TYPE'
} unhandledRejection
TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of ArrayBuffer, Buffer, TypedArray, DataView, KeyObject, or CryptoKey. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at prepareSecretKey (node:internal/crypto/keys:570:11)
    at Cipheriv.createCipherWithIV (node:internal/crypto/cipher:133:9)
    at new Cipheriv (node:internal/crypto/cipher:243:3)
    at Object.createCipheriv (node:crypto:138:10)
    at Object.aesEncrypt (E:\Times\games-wabot\node_modules\@adiwajshing\baileys\lib\WAConnection\Utils.js:108:24)
    at WAConnection.sendBinary (E:\Times\games-wabot\node_modules\@adiwajshing\baileys\lib\WAConnection\0.Base.js:321:26)
    at WAConnection.<anonymous> (E:\Times\games-wabot\node_modules\@adiwajshing\baileys\lib\WAConnection\4.Events.js:89:18)
    at WAConnection.emit (node:events:390:28)
    at WAConnection.emit (E:\Times\games-wabot\node_modules\@adiwajshing\baileys\lib\WAConnection\4.Events.js:664:41) {
  code: 'ERR_INVALID_ARG_TYPE'
} unhandledRejection
TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of ArrayBuffer, Buffer, TypedArray, DataView, KeyObject, or CryptoKey. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at prepareSecretKey (node:internal/crypto/keys:570:11)
    at Cipheriv.createCipherWithIV (node:internal/crypto/cipher:133:9)
    at new Cipheriv (node:internal/crypto/cipher:243:3)
    at Object.createCipheriv (node:crypto:138:10)
    at Object.aesEncrypt (E:\Times\games-wabot\node_modules\@adiwajshing\baileys\lib\WAConnection\Utils.js:108:24)
    at WAConnection.sendBinary (E:\Times\games-wabot\node_modules\@adiwajshing\baileys\lib\WAConnection\0.Base.js:321:26)
    at WAConnection.<anonymous> (E:\Times\games-wabot\node_modules\@adiwajshing\baileys\lib\WAConnection\4.Events.js:90:18)
    at WAConnection.emit (node:events:390:28)
    at WAConnection.emit (E:\Times\games-wabot\node_modules\@adiwajshing\baileys\lib\WAConnection\4.Events.js:664:41) {
  code: 'ERR_INVALID_ARG_TYPE'
} unhandledRejection
TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of ArrayBuffer, Buffer, TypedArray, DataView, KeyObject, or CryptoKey. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at prepareSecretKey (node:internal/crypto/keys:570:11)
    at Cipheriv.createCipherWithIV (node:internal/crypto/cipher:133:9)
    at new Cipheriv (node:internal/crypto/cipher:243:3)
    at Object.createCipheriv (node:crypto:138:10)
    at Object.aesEncrypt (E:\Times\games-wabot\node_modules\@adiwajshing\baileys\lib\WAConnection\Utils.js:108:24)
    at WAConnection.sendBinary (E:\Times\games-wabot\node_modules\@adiwajshing\baileys\lib\WAConnection\0.Base.js:321:26)
    at WAConnection.<anonymous> (E:\Times\games-wabot\node_modules\@adiwajshing\baileys\lib\WAConnection\4.Events.js:91:18)
    at WAConnection.emit (node:events:390:28)
    at WAConnection.emit (E:\Times\games-wabot\node_modules\@adiwajshing\baileys\lib\WAConnection\4.Events.js:664:41) {
  code: 'ERR_INVALID_ARG_TYPE'
} unhandledRejection
TypeError: Cannot read properties of undefined (reading 'toString')
    at WAConnection.base64EncodedAuthInfo (E:\Times\games-wabot\node_modules\@adiwajshing\baileys\lib\WAConnection\0.Base.js:126:42)
    at E:\Times\games-wabot\main.js:105:52
    at processTicksAndRejections (node:internal/process/task_queues:96:5) unhandledRejection
```

**Comment by overfy** [comment]
> @overfy [22f155b](https://github.com/BochilGaming/games-wabot/commit/22f155b8795e1a1f35e7379bd6ad6a9774d80802) ini nge fix gk??

ke fix gan, tapi lemot banget respond bot nya ( di repl & di pc sama aja ) sekitar 1-2 menit an dia baru prosses sampe jadi sticker, tapi kalau perintah kaya /menu dll itu cepet ( normal )

**Comment by overfy** [comment]
> > @overfy [22f155b](https://github.com/BochilGaming/games-wabot/commit/22f155b8795e1a1f35e7379bd6ad6a9774d80802) ini nge fix gk??
> 
> ke fix gan, tapi lemot banget respond bot nya ( di repl & di pc sama aja ) sekitar 1-2 menit an dia baru prosses sampe jadi sticker, tapi kalau perintah kaya /menu dll itu cepet ( normal )

fitur /tiktok juga engga ngerespond gan

**Comment by overfy** [comment]
( Kalau Dari LOG Repl & Di PC, Si Command Sticker ini dia engga langsung kebaca gitu gan, jadi delay gitu beberapa menit )
![Screenshot_266](https://user-images.githubusercontent.com/95896781/151919454-d6cb90ed-c6a0-4939-b18b-21b808a91264.png)

**Comment by unx21** [comment]
> ( Kalau Dari LOG Repl & Di PC, Si Command Sticker ini dia engga langsung kebaca gitu gan, jadi delay gitu beberapa menit ) ![Screenshot_266](https://user-images.githubusercontent.com/95896781/151919454-d6cb90ed-c6a0-4939-b18b-21b808a91264.png)

Yang penting work dulu

**Comment by BochilGaming** [comment]
> > > @overfy [22f155b](https://github.com/BochilGaming/games-wabot/commit/22f155b8795e1a1f35e7379bd6ad6a9774d80802) ini nge fix gk??
> > 
> > 
> > ke fix gan, tapi lemot banget respond bot nya ( di repl & di pc sama aja ) sekitar 1-2 menit an dia baru prosses sampe jadi sticker, tapi kalau perintah kaya /menu dll itu cepet ( normal )
> 
> fitur /tiktok juga engga ngerespond gan

 fbb4c57 nge fix gk?

**Comment by overfy** [comment]
![Screenshot_267](https://user-images.githubusercontent.com/95896781/151946360-d49e5eb7-8e3e-4534-94c9-2ac3b578ddf6.png)

belum gan, tapi gapapa, yg penting stickernya udah jalan dulu


> > > > @overfy [22f155b](https://github.com/BochilGaming/games-wabot/commit/22f155b8795e1a1f35e7379bd6ad6a9774d80802) ini nge fix gk??
> > > 
> > > 
> > > ke fix gan, tapi lemot banget respond bot nya ( di repl & di pc sama aja ) sekitar 1-2 menit an dia baru prosses sampe jadi sticker, tapi kalau perintah kaya /menu dll itu cepet ( normal )
> > 
> > 
> > fitur /tiktok juga engga ngerespond gan
> 
> [fbb4c57](https://github.com/BochilGaming/games-wabot/commit/fbb4c578968a122cdc886781b64622faa9f489c7) nge fix gk?

**Comment by BochilGaming** [comment]
Pastiin module @bochilteam/scraper udh ke install dan udh versi terbaru npm
