### ISSUE TITLE
bug qrcode

### ISSUE THREAD

**Issue by kwteen** [BochilGaming/games-wabot#332]
at prepareSecretKey (internal/crypto/keys.js:322:11)
    at Cipheriv.createCipherWithIV (internal/crypto/cipher.js:119:9)
    at new Cipheriv (internal/crypto/cipher.js:227:22)
    at Object.createCipheriv (crypto.js:122:10)
    at Object.aesEncrypt (C:\games-wabot\games-wabot\node_modules\@adiwajshing\baileys\lib\WAConnection\Utils.js:112:24)
    at WAConnection.sendBinary (C:\games-wabot\games-wabot\node_modules\@adiwajshing\baileys\lib\WAConnection\0.Base.js:325:26)
    at WAConnection.<anonymous> (C:\games-wabot\games-wabot\node_modules\@adiwajshing\baileys\lib\WAConnection\4.Events.js:94:18)
    at WAConnection.emit (events.js:400:28)
    at WAConnection.emit (C:\games-wabot\games-wabot\node_modules\@adiwajshing\baileys\lib\WAConnection\4.Events.js:668:41)
(node:7016) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
(node:7016) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of Buffer, TypedArray, DataView, or KeyObject. Received undefined
    at new NodeError (internal/errors.js:322:7)
    at prepareSecretKey (internal/crypto/keys.js:322:11)
    at Cipheriv.createCipherWithIV (internal/crypto/cipher.js:119:9)
    at new Cipheriv (internal/crypto/cipher.js:227:22)
    at Object.createCipheriv (crypto.js:122:10)
    at Object.aesEncrypt (C:\games-wabot\games-wabot\node_modules\@adiwajshing\baileys\lib\WAConnection\Utils.js:112:24)
    at WAConnection.sendBinary (C:\games-wabot\games-wabot\node_modules\@adiwajshing\baileys\lib\WAConnection\0.Base.js:325:26)
    at WAConnection.<anonymous> (C:\games-wabot\games-wabot\node_modules\@adiwajshing\baileys\lib\WAConnection\4.Events.js:95:18)
    at WAConnection.emit (events.js:400:28)
    at WAConnection.emit (C:\games-wabot\games-wabot\node_modules\@adiwajshing\baileys\lib\WAConnection\4.Events.js:668:41)
(node:7016) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
(node:7016) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toString' of undefined
    at WAConnection.base64EncodedAuthInfo (C:\games-wabot\games-wabot\node_modules\@adiwajshing\baileys\lib\WAConnection\0.Base.js:130:42)
    at C:\games-wabot\games-wabot\main.js:107:52
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(node:7016) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 7)
INFO [2022-05-14 02:41:50.795 +0000] (7016): closed connection, reason close, reconnecting in a few seconds...
    class: "Baileys"
INFO [2022-05-14 02:41:56.322 +0000] (7016): connected to WhatsApp Web server, authenticating via takeover
    class: "Baileys"
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄

**Comment by BochilGaming** [comment]
try use multi-device branch or [this](https://github.com/BochilGaming/games-wabot-md)

**Comment by Bintangp02** [comment]
Mungkin perangkat yang anda belum tertaut dengan multi device dan gunakan branch [Klik di sini](https://github.com/BochilGaming/games-wabot-md)
