### ISSUE TITLE
Gini ngab

### ISSUE THREAD

**Issue by senotdev** [BochilGaming/games-wabot#382]
class: "Baileys"                                  (node:45393) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of Buffer, TypedArray, DataView, or KeyObject. Received undefined                 at prepareSecretKey (internal/crypto/keys.js:322:11)                                                        at Cipheriv.createCipherWithIV (internal/crypto/cipher.js:119:9)                                            at new Cipheriv (internal/crypto/cipher.js:227:22)    at Object.createCipheriv (crypto.js:123:10)           at Object.aesEncrypt (/root/wabot-aq/node_modules/@adiwajshing/baileys/lib/WAConnection/Utils.js:108:24)    at WAConnection.sendBinary (/root/wabot-aq/node_modules/@adiwajshing/baileys/lib/WAConnection/0.Base.js:321:26)                                                   at WAConnection.<anonymous> (/root/wabot-aq/node_modules/@adiwajshing/baileys/lib/WAConnection/4.Events.js:86:18)                                                 at WAConnection.emit (events.js:314:20)               at WAConnection.emit (/root/wabot-aq/node_modules/@adiwajshing/baileys/lib/WAConnection/4.Events.js:664:41)                                                       at WAConnection.connect (/root/wabot-aq/node_modules/@adiwajshing/baileys/lib/WAConnection/3.Connect.js:70:14)                                                (Use `node --trace-warnings ...` to show where the warning was created)
(node:45393) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)    (node:45393) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.            (node:45393) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of Buffer, TypedArray, DataView, or KeyObject. Received undefined                 at prepareSecretKey (internal/crypto/keys.js:322:11)                                                        at Cipheriv.createCipherWithIV (internal/crypto/cipher.js:119:9)                                            at new Cipheriv (internal/crypto/cipher.js:227:22)    at Object.createCipheriv (crypto.js:123:10)           at Object.aesEncrypt (/root/wabot-aq/node_modules/@adiwajshing/baileys/lib/WAConnection/Utils.js:108:24)    at WAConnection.sendBinary (/root/wabot-aq/node_modules/@adiwajshing/baileys/lib/WAConnection/0.Base.js:321:26)                                                   at WAConnection.<anonymous> (/root/wabot-aq/node_modules/@adiwajshing/baileys/lib/WAConnection/4.Events.js:87:18)                                                 at WAConnection.emit (events.js:314:20)               at WAConnection.emit (/root/wabot-aq/node_modules/@adiwajshing/baileys/lib/WAConnection/4.Events.js:664:41)                                                       at WAConnection.connect (/root/wabot-aq/node_modules/@adiwajshing/baileys/lib/WAConnection/3.Connect.js:70:14)                                                (node:45393) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)    (node:45393) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of Buffer, TypedArray, DataView, or KeyObject. Received undefined                 at prepareSecretKey (internal/crypto/keys.js:322:11)                                                        at Cipheriv.createCipherWithIV (internal/crypto/cipher.js:119:9)                                            at new Cipheriv (internal/crypto/cipher.js:227:22)    at Object.createCipheriv (crypto.js:123:10)           at Object.aesEncrypt (/root/wabot-aq/node_modules/@adiwajshing/baileys/lib/WAConnection/Utils.js:108:24)    at WAConnection.sendBinary (/root/wabot-aq/node_modules/@adiwajshing/baileys/lib/WAConnection/0.Base.js:321:26)
    at WAConnection.<anonymous> (/root/wabot-aq/node_modules/@adiwajshing/baileys/lib/WAConnection/4.Events.js:88:18)                                                 at WAConnection.emit (events.js:314:20)               at WAConnection.emit (/root/wabot-aq/node_modules/@adiwajshing/baileys/lib/WAConnection/4.Events.js:664:41)                                                       at WAConnection.connect (/root/wabot-aq/node_modules/@adiwajshing/baileys/lib/WAConnection/3.Connect.js:70:14)                                                (node:45393) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)    (node:45393) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of Buffer, TypedArray, DataView, or KeyObject. Received undefined                 at prepareSecretKey (internal/crypto/keys.js:322:11)                                                        at Cipheriv.createCipherWithIV (internal/crypto/cipher.js:119:9)
    at new Cipheriv (internal/crypto/cipher.js:227:22)    at Object.createCipheriv (crypto.js:123:10)
    at Object.aesEncrypt (/root/wabot-aq/node_modules/@adiwajshing/baileys/lib/WAConnection/Utils.js:108:24)    at WAConnection.sendBinary (/root/wabot-aq/node_modules/@adiwajshing/baileys/lib/WAConnection/0.Base.js:321:26)                                                   at WAConnection.<anonymous> (/root/wabot-aq/node_modules/@adiwajshing/baileys/lib/WAConnection/4.Events.js:89:18)                                                 at WAConnection.emit (events.js:314:20)
    at WAConnection.emit (/root/wabot-aq/node_modules/@adiwajshing/baileys/lib/WAConnection/4.Events.js:664:41)                                                       at WAConnection.connect (/root/wabot-aq/node_modules/@adiwajshing/baileys/lib/WAConnection/3.Connect.js:70:14)                                                (node:45393) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
(node:45393) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of Buffer, TypedArray, DataView, or KeyObject. Received undefined                 at prepareSecretKey (internal/crypto/keys.js:322:11)                                                        at Cipheriv.createCipherWithIV (internal/crypto/cipher.js:119:9)                                            at new Cipheriv (internal/crypto/cipher.js:227:22)
    at Object.createCipheriv (crypto.js:123:10)           at Object.aesEncrypt (/root/wabot-aq/node_modules/@adiwajshing/baileys/lib/WAConnection/Utils.js:108:24)    at WAConnection.sendBinary (/root/wabot-aq/node_modules/@adiwajshing/baileys/lib/WAConnection/0.Base.js:321:26)                                                   at WAConnection.<anonymous> (/root/wabot-aq/node_modules/@adiwajshing/baileys/lib/WAConnection/4.Events.js:90:18)                                                 at WAConnection.emit (events.js:314:20)               at WAConnection.emit (/root/wabot-aq/node_modules/@adiwajshing/baileys/lib/WAConnection/4.Events.js:664:41)                                                       at WAConnection.connect (/root/wabot-aq/node_modules/@adiwajshing/baileys/lib/WAConnection/3.Connect.js:70:14)                                                (node:45393) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)    (node:45393) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of Buffer, TypedArray, DataView, or KeyObject. Received undefined                 at prepareSecretKey (internal/crypto/keys.js:322:11)
    at Cipheriv.createCipherWithIV (internal/crypto/cipher.js:119:9)                                            at new Cipheriv (internal/crypto/cipher.js:227:22)    at Object.createCipheriv (crypto.js:123:10)           at Object.aesEncrypt (/root/wabot-aq/node_modules/@adiwajshing/baileys/lib/WAConnection/Utils.js:108:24)    at WAConnection.sendBinary (/root/wabot-aq/node_modules/@adiwajshing/baileys/lib/WAConnection/0.Base.js:321:26)                                                   at WAConnection.<anonymous> (/root/wabot-aq/node_modules/@adiwajshing/baileys/lib/WAConnection/4.Events.js:91:18)                                                 at WAConnection.emit (events.js:314:20)               at WAConnection.emit (/root/wabot-aq/node_modules/@adiwajshing/baileys/lib/WAConnection/4.Events.js:664:41)                                                       at WAConnection.connect (/root/wabot-aq/node_modules/@adiwajshing/baileys/lib/WAConnection/3.Connect.js:70:14)                                                (node:45393) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)    (node:45393) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toString' of undefined          at WAConnection.base64EncodedAuthInfo (/root/wabot-aq/node_modules/@adiwajshing/baileys/lib/WAConnection/0.Base.js:126:42)
    at /root/wabot-aq/main.js:107:52                      at processTicksAndRejections (internal/process/task_queues.js:93:5)                                     (node:45393) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 8)

**Comment by BochilGaming** [comment]
Duplicate #332, read [this](https://github.com/BochilGaming/games-wabot/tree/multi-device#faq)
