### ISSUE TITLE
SyntaxError: Unexpected reserved word

### ISSUE THREAD

**Issue by sandemoit** [BochilGaming/games-wabot#403]
ini kenpaaya pas jalanin node .

file:///home/sandi/games-wabot/main.js:42
  value: await Connection.conn,
         ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)
Exited with code: null

**Comment by Goldn7799** [comment]
Update nodejs nya pake versi 16 keatas
