### ISSUE TITLE
not working, I cant loggin.

### ISSUE THREAD

**Issue by Alizee187** [BochilGaming/games-wabot#407]
{"level":30,"time":"2022-10-25T17:17:32.103Z","pid":28441,"hostname":"vps-2926839-x","class":"baileys","trace":"Error: Stream Errored (restart required)\n    at WebSocket.<anonymous> (/root/kata/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:415:13)\n    at WebSocket.emit (node:events:513:28)\n    at /root/kata/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:221:35\n    at Object.decodeFrame (/root/kata/node_modules/@adiwajshing/baileys/lib/Utils/noise-handler.js:131:17)\n    at WebSocket.onMessageRecieved (/root/kata/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:197:15)\n    at WebSocket.emit (node:events:513:28)\n    at Receiver.receiverOnMessage (/root/kata/node_modules/ws/lib/websocket.js:1178:20)\n    at Receiver.emit (node:events:513:28)\n    at Receiver.dataMessage (/root/kata/node_modules/ws/lib/receiver.js:513:14)\n    at Receiver.getData (/root/kata/node_modules/ws/lib/receiver.js:446:17)","msg":"connection errored"}

**Comment by Alizee187** [comment]
![image](https://user-images.githubusercontent.com/70238672/197840222-340564f8-f270-496a-a685-27f73652adf8.png)

**Comment by Goldn7799** [comment]
Use multi-device for new whatsapp version
